version: '3.8'

services:
  ts-qbittorrent:
    image: tailscale/tailscale:latest
    container_name: ts-qbittorrent
    hostname: qbittorrent
    environment:
      - TS_AUTHKEY=la-mia-chiave # Inserisci la tua chiave Tailscale
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - tailscale_data_qbittorrent:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=9001
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-config:/config
      - /home/samoggino/Video/tmp:/downloads #optional
    restart: unless-stopped
    network_mode: service:ts-qbittorrent

volumes:
  qbittorrent-config:
  tailscale_data_qbittorrent:
    driver: local
