services:
  ts-qbittorrent:
    image: tailscale/tailscale:latest
    container_name: ts-qbittorrent
    hostname: qbittorrent
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false

    volumes:
      - ts-qbit-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=9001
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-config:/config
      - /home/samoggino/Video/tmp:/downloads #caching
      - /mnt/Elements/serie-simo:/serie
      - /mnt/Elements/film-simo:/film
    restart: unless-stopped
    network_mode: service:ts-qbittorrent

volumes:
  qbittorrent-config:
    external: true
  ts-qbit-data:
    external: true

