FROM php:latest

# Imposta la directory di lavoro
WORKDIR /home/samoggino/Scrivania/docker/basi-docker

# Specifica il comando di avvio per il server web PHP sulla porta 8081
CMD ["php", "-S", "0.0.0.0:8081", "-t", "."]
