services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - beszel-data:/beszel_data
volumes:
  beszel-data:
    external: true
    
